---
Name: menuconfig
Only:
  moduleexists: silverstripe/subsite
---
gorriecoe\Menu\Models\MenuSet:
  extensions:
    - gorriecoe\Menu\Extensions\MenuSetSubsiteExtension
---
Only:
  moduleexists: 'silverstripe/graphql'
---
SilverStripe\GraphQL\Controller:
  schema:
    scaffolding_providers:
      - gorriecoe\Menu\Models\MenuSet
      - gorriecoe\Menu\Models\MenuLink
